from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from visionpack.core.errors import ManifestError
from visionpack.core.models import ClassDef


@dataclass(slots=True)
class Manifest:
    name: str
    version: int = 1
    task: str = "detection"
    classes: list[ClassDef] = field(default_factory=list)
    storage: dict[str, Any] = field(default_factory=lambda: {"mode": "content-addressed", "hash": "sha256"})
    validation: dict[str, Any] = field(default_factory=dict)
    splits: dict[str, Any] = field(default_factory=dict)
    exports: dict[str, Any] = field(default_factory=dict)
    pack_profiles: dict[str, Any] = field(default_factory=dict)
    annotation: dict[str, Any] = field(default_factory=dict)

    @classmethod
    def default(cls, name: str, task: str = "detection") -> "Manifest":
        return cls(
            name=name,
            task=task,
            validation={
                "require_annotations": False,
                "allow_empty_images": True,
                "bbox": {"min_area_px": 4, "allow_out_of_bounds": False},
                "splits": {"prevent_leakage": True},
                "duplicates": {"exact": "warn", "perceptual": "off"},
            },
            splits={"default": {"strategy": "random", "train": 0.8, "val": 0.1, "test": 0.1}},
            exports={
                "yolo": {"image_format": "original", "normalized_coordinates": True},
                "coco": {"include_empty_images": True},
            },
            pack_profiles={
                "archive": {"format": "tar", "include_metadata": True},
                "training": {"format": "folder", "shard_size": 1024},
            },
            annotation={"preferred_tool": "cvat", "review_required": True},
        )

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Manifest":
        if "name" not in data:
            raise ManifestError("visionpack.yaml is missing required field: name")
        return cls(
            name=str(data["name"]),
            version=int(data.get("version", 1)),
            task=str(data.get("task", "detection")),
            classes=[ClassDef.from_dict(item) for item in data.get("classes", [])],
            storage=dict(data.get("storage", {"mode": "content-addressed", "hash": "sha256"})),
            validation=dict(data.get("validation", {})),
            splits=dict(data.get("splits", {})),
            exports=dict(data.get("exports", {})),
            pack_profiles=dict(data.get("pack_profiles", {})),
            annotation=dict(data.get("annotation", {})),
        )

    def to_dict(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "version": self.version,
            "task": self.task,
            "classes": [item.to_dict() for item in self.classes],
            "storage": self.storage,
            "validation": self.validation,
            "splits": self.splits,
            "exports": self.exports,
            "pack_profiles": self.pack_profiles,
            "annotation": self.annotation,
        }

    @property
    def class_ids(self) -> set[str]:
        return {item.id for item in self.classes}

    def ensure_classes(self, class_names: list[str]) -> bool:
        if self.classes:
            return False
        self.classes = [ClassDef(id=_class_id(name), name=name) for name in class_names]
        return True

    def class_id_for_index(self, index: int) -> str:
        if 0 <= index < len(self.classes):
            return self.classes[index].id
        return f"class_{index}"


def read_manifest(path: Path) -> Manifest:
    if not path.exists():
        raise ManifestError(f"Manifest not found: {path}")
    text = path.read_text(encoding="utf-8")
    data = _loads_mapping(text)
    return Manifest.from_dict(data)


def write_manifest(path: Path, manifest: Manifest) -> None:
    path.write_text(_dump_yaml(manifest.to_dict()), encoding="utf-8")


def _class_id(name: str) -> str:
    clean = "".join(ch.lower() if ch.isalnum() else "_" for ch in name.strip())
    clean = "_".join(part for part in clean.split("_") if part)
    return clean or "class"


def _loads_mapping(text: str) -> dict[str, Any]:
    try:
        import yaml  # type: ignore

        loaded = yaml.safe_load(text) or {}
        if not isinstance(loaded, dict):
            raise ManifestError("visionpack.yaml must contain a mapping at the top level")
        return loaded
    except ModuleNotFoundError:
        return _parse_limited_yaml(text)


def _parse_limited_yaml(text: str) -> dict[str, Any]:
    """Parse the YAML subset generated by VisionPack when PyYAML is absent."""
    result: dict[str, Any] = {}
    lines = [line.rstrip() for line in text.splitlines() if line.strip() and not line.lstrip().startswith("#")]
    current_key: str | None = None
    current_list: list[dict[str, Any]] | None = None
    for line in lines:
        if not line.startswith(" ") and ":" in line:
            key, value = line.split(":", 1)
            current_key = key.strip()
            value = value.strip()
            if value == "":
                if current_key == "classes":
                    current_list = []
                    result[current_key] = current_list
                else:
                    result[current_key] = {}
                    current_list = None
            else:
                result[current_key] = _scalar(value)
                current_list = None
        elif current_key == "classes" and current_list is not None:
            stripped = line.strip()
            if stripped.startswith("- "):
                key, value = stripped[2:].split(":", 1)
                current_list.append({key.strip(): _scalar(value.strip())})
            elif current_list and ":" in stripped:
                key, value = stripped.split(":", 1)
                current_list[-1][key.strip()] = _scalar(value.strip())
    return result


def _scalar(value: str) -> Any:
    if value in {"true", "false"}:
        return value == "true"
    if value == "null":
        return None
    try:
        return int(value)
    except ValueError:
        pass
    try:
        return float(value)
    except ValueError:
        pass
    if value.startswith("[") or value.startswith("{"):
        return json.loads(value)
    return value.strip('"')


def _dump_yaml(data: dict[str, Any], indent: int = 0) -> str:
    lines: list[str] = []
    pad = " " * indent
    for key, value in data.items():
        if isinstance(value, dict):
            lines.append(f"{pad}{key}:")
            lines.append(_dump_yaml(value, indent + 2).rstrip())
        elif isinstance(value, list):
            lines.append(f"{pad}{key}:")
            for item in value:
                if isinstance(item, dict):
                    first = True
                    for child_key, child_value in item.items():
                        prefix = "- " if first else "  "
                        lines.append(f"{pad}  {prefix}{child_key}: {_format_scalar(child_value)}")
                        first = False
                else:
                    lines.append(f"{pad}  - {_format_scalar(item)}")
        else:
            lines.append(f"{pad}{key}: {_format_scalar(value)}")
    return "\n".join(lines) + "\n"


def _format_scalar(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if value is None:
        return "null"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, (dict, list)):
        return json.dumps(value, sort_keys=True)
    text = str(value)
    if not text or any(ch in text for ch in ":#[]{}"):
        return json.dumps(text)
    return text
