from __future__ import annotations

import shutil
from pathlib import Path

from visionpack.core.errors import ProjectNotFoundError
from visionpack.core.manifest import Manifest, read_manifest, write_manifest
from visionpack.index import Index
from visionpack.storage.object_store import ObjectStore


class Project:
    def __init__(self, root: Path) -> None:
        self.root = root.resolve()
        self.manifest_path = self.root / "visionpack.yaml"
        if not self.manifest_path.exists():
            raise ProjectNotFoundError(f"No visionpack.yaml found at {self.root}")
        self.manifest = read_manifest(self.manifest_path)
        self.index = Index(self.root)
        self.object_store = ObjectStore(self.root)

    @classmethod
    def open(cls, root: str | Path = ".") -> "Project":
        root_path = Path(root).resolve()
        manifest = _find_manifest(root_path)
        if manifest is None:
            raise ProjectNotFoundError("No VisionPack project found. Run `vp init` first.")
        return cls(manifest.parent)

    @classmethod
    def init(cls, root: str | Path = ".", name: str | None = None, task: str = "detection") -> "Project":
        root_path = Path(root).resolve()
        root_path.mkdir(parents=True, exist_ok=True)
        dataset_name = name or root_path.name
        manifest_path = root_path / "visionpack.yaml"
        if not manifest_path.exists():
            write_manifest(manifest_path, Manifest.default(dataset_name, task))
        # Git-like layout: the only things created up front are the manifest and
        # the `.vp/` control directory. Output dirs (exports/, reports/) are made
        # on demand by the commands that write them, so the project root stays
        # clean and the manifest + index remain the single source of truth.
        for directory in [
            root_path / ".vp" / "db",
            root_path / ".vp" / "objects",
            root_path / ".vp" / "snapshots",
        ]:
            directory.mkdir(parents=True, exist_ok=True)
        _ensure_gitignore(root_path / ".gitignore")
        project = cls(root_path)
        project.index.save()
        return project

    def save_manifest(self) -> None:
        write_manifest(self.manifest_path, self.manifest)

    def materialize_asset(self, asset_path: Path, output_path: Path) -> None:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(asset_path, output_path)


Dataset = Project


# What to keep under version control vs. ignore. The manifest, the index
# (.vp/db), and snapshots (.vp/snapshots) are the reproducible source of truth and
# stay tracked. Ingested asset bytes, caches, logs, and derived outputs are heavy
# and/or regenerable, so they are ignored — a clone can rebuild assets with
# `vp sync`.
_GITIGNORE = """\
# VisionPack — keep visionpack.yaml, .vp/db (index) and .vp/snapshots tracked.

# Ingested asset bytes — large; rebuilt from declared sources with `vp sync`.
.vp/objects/

# Ephemeral
.vp/cache/
.vp/logs/
.vp/lock

# Derived outputs (regenerated by export / pack / validate --report)
/exports/
/reports/
"""


def _ensure_gitignore(path: Path) -> None:
    # Never clobber a .gitignore the user already maintains.
    if not path.exists():
        path.write_text(_GITIGNORE, encoding="utf-8")


def _find_manifest(start: Path) -> Path | None:
    current = start
    while True:
        candidate = current / "visionpack.yaml"
        if candidate.exists():
            return candidate
        if current.parent == current:
            return None
        current = current.parent
